# Generated by Django 5.2 on 2025-05-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='userId',
        ),
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.CharField(choices=[('F', 'Free'), ('B', 'Basic'), ('P', 'Premium')], default='F', max_length=1, null=True),
        ),
    ]
