# Generated by Django 5.2 on 2025-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_member_userid_member_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='emailAddress',
            field=models.EmailField(max_length=254),
        ),
    ]
