"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import logging
import sys
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lpnplpt2s_lp+4p71_z!2)@hf!e*(vykraf6**khxz+&(s3&g6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']    
# テスト用途なら ['*'] でも通ります（本番では×）

# セッション設定
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # サーバー側DB
CSRF_COOKIE_HTTPONLY = False # JSでアクセス可能（API連携のため）
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_HTTPONLY = True         # JSでアクセスできない
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = False  # ローカル開発時のみ。HTTPSならTrue推奨

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'corsheaders',

    # 自作アプリ（apps/配下）
    'apps.ai',
    'apps.analytics',
    'apps.core',
    'apps.history',
    'apps.stocks',
    'apps.subscription',
    'apps.users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://10.192.95.26:3000",  # 開発中フロント（IP指定）
    # "https://your-frontend.com",  # 本番フロント（将来追加）
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'users.Member'  # カスタムユーザーモデルを指定

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# データ格納ディレクトリ
STOCK_DATA_DIR = BASE_DIR / 'stock_data'
RAW_DATA_DIR = STOCK_DATA_DIR / 'raw_data'
ANALYTICS_DATA_DIR = STOCK_DATA_DIR / 'analytics_data'
PROCESSED_DATA_DIR = STOCK_DATA_DIR / 'processed_data'
LEARNING_DATA_DIR = STOCK_DATA_DIR / 'learning_data'

#クラスインスタンス
from apps.stocks.services.parquet_handler import ParquetHandler
PARQUET_HANDLER = ParquetHandler()


# モデル格納ディレクトリ
MODEL_DIR = BASE_DIR / 'apps' / 'ai' / 'ai_models' 

# ログ出力ディレクトリ
LOG_DIR = BASE_DIR / 'logs'
RESEARCH_DATA_DIR = LOG_DIR / 'research_data'

# ログ設定
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[{asctime}] {levelname} {name} | {module}.{funcName}:{lineno} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',  # 全部表示
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'default',
        },
        'error_file': {
            'level': 'ERROR',  # ERROR以上のみ記録
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / 'error.log'),
            'formatter': 'default',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'apps': {
            'handlers': ['console', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
# ノートブック（AI/分析用）
NOTEBOOK_DIR = BASE_DIR / 'notebooks'

# Django REST Frameworkの設定
# ここではJSONレンダラーのみを使用する設定
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}
# mail設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# ホスト
EMAIL_HOST = os.getenv('SMTP_SERVER')
# SMTPサーバーのポート番号
EMAIL_PORT = int(os.getenv('SMTP_PORT', 587))
EMAIL_HOST_USER = os.getenv('SENDER_EMAIL')
# SMTPサーバーのパスワード (アプリパスワードを推奨)
EMAIL_HOST_PASSWORD = os.getenv('SENDER_PASSWORD')
# TLS/SSL暗号化を使用するかどうか
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = os.getenv('SENDER_EMAIL')
SERVER_EMAIL = os.getenv('SENDER_EMAIL')
