# Generated by Django 5.2 on 2025-05-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='このセクターの説明')),
            ],
        ),
        migrations.CreateModel(
            name='SectorFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_per', models.FloatField(help_text='平均PER（株価収益率）')),
                ('avg_eps_growth', models.FloatField(help_text='平均EPS成長率（%）')),
                ('avg_market_cap', models.BigIntegerField(help_text='平均時価総額（円 or ドル単位）')),
                ('geopolitical_risk_score', models.FloatField(help_text='地政学的リスクスコア（0〜1）')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.sector')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('sector', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SectorTrendScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sentiment_score', models.FloatField(help_text='感情スコア（-1〜+1）')),
                ('mention_count', models.IntegerField(help_text='SNS・ニュース等での出現回数')),
                ('volume_change_pct', models.FloatField(help_text='前日比での出来高変化率（%）')),
                ('volatility', models.FloatField(help_text='価格のボラティリティ（標準偏差や変動幅など）')),
                ('news_keywords', models.JSONField(blank=True, default=list, help_text='関連ニュースキーワードリスト')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.sector')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('sector', 'date')},
            },
        ),
    ]
