# Generated by Django 5.2 on 2025-05-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSuccessRate',
            fields=[
                ('field_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('total_success_rate', models.FloatField(default=0.0)),
                ('count', models.IntegerField(default=0)),
                ('source', models.CharField(default='info', max_length=64)),
                ('date_measured', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_success_rate',
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=20)),
                ('predicted_price', models.FloatField()),
                ('actual_price', models.FloatField()),
                ('error', models.FloatField()),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'ticker', 'model_version')},
            },
        ),
    ]
